# Generated by Django 4.1.7 on 2023-04-01 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_author_id_author_age_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.author'),
        ),
    ]
