# Generated by Django 4.1.7 on 2023-04-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='age',
            new_name='idade',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='publishing_company',
            new_name='campanha_publicitária',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='create_at',
            new_name='criado_por',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='pages',
            new_name='data_de_publicação',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='id_book',
            new_name='id_do_livro',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='release_year',
            new_name='página',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='title',
            new_name='título',
        ),
    ]
