# Generated by Django 4.1.7 on 2023-04-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_age_author_idade_rename_name_author_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='campanha_publicitária',
        ),
    ]
